[package]
name = "gatos-ledger-core"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1.5"
heapless = "0.8" # For no_std collections
bincode = "1.3" # For serialization
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_with = { version = "3.8", default-features = false, features = ["macros"] }
